### ISSUE TITLE
Add option to physically delete journal messages

### ISSUE THREAD

**Issue by eshepelyuk** [dnvriend/akka-persistence-jdbc#160] opened 2018-01-05 15:25 UTC
Currently journal items are marked as deleted when `akka.persistence.Eventsourced#deleteMessages` is called. It happens inside `akka.persistence.jdbc.journal.dao.BaseByteArrayJournalDao#delete` method.

When it comes to bigger amounts of journal items being written and deleted (after snapshot, e.g.) this functionality may bring operational issue resulting in lack of disk space on DB server.

What do you think about introducing a configuration setting that will instruct `JournalDao` to physically delete journal items from DB, not just mark them as deleted.

For instance `cassandra` journal implementation does permanent deletion by default [see here](https://github.com/krasserm/akka-persistence-cassandra/blob/master/src/main/scala/akka/persistence/cassandra/journal/CassandraStatements.scala)

@dnvriend do you assume any technical or architectural drawback in this proposal ?

**Comment by WellingR** [comment] 2018-01-05 17:32
Such a configuration setting could be useful, however this has the drawback that these events are no longer returned for the eventsByTag query. (which may or may not be desisired).

Currently this is not supported, but it should definitely be possible to introduce this feature based on a configuration setting.

I added the "help wanted label" since I will not have the time to work on this soon.

**Comment by eshepelyuk** [comment] 2018-01-05 17:36
Hello @WellingR 

me and my co-workers are willing to provide a PR for that. Is it interesting to you ?
If yes, plz assign it to me (if `GitHub` allows it) so we're ready to start working on this feature.

**Comment by WellingR** [comment] 2018-01-06 21:12
Yes, this would be much appreciated. I have assigned this issue to you

**Comment by renatocaval** [comment] 2018-01-09 13:53
There is a related discussion on this PR (never merged and now apparently abandoned)
https://github.com/dnvriend/akka-persistence-jdbc/pull/104

**Closed** 2018-01-12 07:17 UTC
Labels: enhancement, help wanted

**Comment by eshepelyuk** [comment] 2018-01-12 10:02
@renatocaval @WellingR thanks you for accepting the PR,
May we expect a new release with that fix appear soon ?

**Comment by WellingR** [comment] 2018-01-12 19:43
Since it makes sense to include the changes from #104 in combination with this. We will probably make a similar change to allow configuration of whether to return deleted events in queries. When this is done a release can be made.

**Comment by eshepelyuk** [comment] 2018-01-17 08:17
Hi @WellingR 

This sounds reasonable, except the fact that referenced PR was not updated since 13 Nov of the last year.
I'm just worried that it can take ages for #104 to be resolved and for both features to be released.

From the other hand - this issue (#160) released on its own will not affect existing users at all.
Additionally the warning can be added into docs explaining that setting `logicalDelete = false` may lead to unexpected behavior until #104 is not resolved.

I'm not sure about your current plans regarding resolving #104 but if you think it can take a while to complete, maybe you guys can think about releasing a new version before closing #104.

Thanks in advance.

**Comment by renatocaval** [comment] 2018-01-17 10:27
@eshepelyuk is it not much work to make #104 happens. I will try to take a look today.

**Comment by eshepelyuk** [comment] 2018-01-17 11:24
Thank you @renatocaval

**Comment by renatocaval** [comment] 2018-01-19 15:06
@eshepelyuk I fixed the conflict in #104, but didn't find enough time to work on it further. I'm facing some issues with Oracle docker and we need to add tests to make sure we aren't introducing any regression. Bottom line, I can't implement is as fast I as thought. 

Maybe we should simple cut a release with #160 as you mentioned and #104 comes in a the next one. 

@WellingR what do you think? Do we cut a new release?

**Comment by WellingR** [comment] 2018-01-19 16:48
@renatocaval We can make a new release. I will see if I can do it this weekend

**Comment by WellingR** [comment] 2018-01-22 10:06
@eshepelyuk The 3.2.0 release has been published to bintray. It may take a few hours before it is synchronized to maven central.

**Comment by eshepelyuk** [comment] 2018-01-23 06:34
Hi @WellingR 
Thank you for releasing. We'll start using it soon.
Btw there's a minor mistake in README - to delete messages physically `logicalDelete` must be set to false. 
Not true as mentioned in readme (this is default)

**Comment by WellingR** [comment] 2018-01-23 07:53
@eshepelyuk Thanks for noticing this. I have corrected the release notes.
