### ISSUE TITLE
Ability to use custom connection pool

### ISSUE THREAD

**Issue by prettynatty** [dnvriend/akka-persistence-jdbc#24] opened 2015-08-09 02:05 UTC
[We](https://github.com/actorapp/actor-platform) are using akka-persistence-jdbc as default akka persistence layer but also our app uses Slick with HikariCP for some business logic, so the app uses two pools at the same time. Would be useful to have an ability to make akka-persistence-jdbc to use external connection pool.
We can contribute it, and I am bringing the issue here to discuss how API should look like. Do you have an advise?

**Comment by prettynatty** [comment] 2015-08-09 02:11
Just found out that akka-persistence-jdbc supports JNDI. We'll test it out.

**Comment by dnvriend** [comment] 2015-08-15 09:09
This is a duplicate of issue #12 that already has been fixed by means of JNDI. Let me know if it works for you!

**Closed by dnvriend** 2015-08-15 09:09 UTC
Labels: duplicate
