### ISSUE TITLE
2.12 support

### ISSUE THREAD

**Issue by TimPigden** [dnvriend/akka-persistence-jdbc#87] opened 2016-12-20 13:47 UTC
Hi, what's the situation of 2.12 support? Any timetable? Slick 3.2.0M2 now does it I see.
Apologies if this has been asked elsewhere but couldn't see anything

**Comment by dnvriend** [comment] 2016-12-20 16:45
No worries :). ETA, the release date of Slick 3.2 + the time necessary to get things working flawlessly with it.

**Comment by dnvriend** [comment] 2016-12-21 18:12
I've released a test version `2.6.12-3.2.0-M2` only available on bintray so add a resolver to `resolvers += Resolver.jcenterRepo`. Its a version against a Milestone release of Slick 3.2.0-M2 for scala 2.11.8 and 2.12.1 only to tinker with.

**Comment by markschaake** [comment] 2017-02-24 19:32
FYI, slick 3.2 was [released](http://slick.lightbend.com/news/2017/02/24/slick-3.2.0-released.html) today. Hopefully we can get a scala 2.12 release soon for `akka-persistence-jdbc`? FYI, I previously tested the above-mentioned `2.6.12-3.2.0-M2` release of `akka-persistence-jdbc` and had issues, so figured I'd wait until the official releases to upgrade to scala 2.12. I'll see if I can test out the `2.6.12-3.2.0-M2` release of `akka-persistence-jdbc` release against the official Slick `3.2` release to see if the issues I saw before are magically gone.

**Comment by dnvriend** [comment] 2017-02-24 20:13
I have released 2.4.17.1 that should support Slick 3.2.0, Scala 2.11.8 and 2.12.1.

**Comment by markschaake** [comment] 2017-02-25 00:15
@dnvriend I've just tried upgrading to both Slick `3.2.0` and `akka-persistece-jdbc` `2.4.17.1` and hit the same issue I hit when I previously tried to upgrade to the `M2` versions. Looks like I'm hitting [this failed requirement](https://github.com/slick/slick/blob/f14199dc1f6b3f415a4233ce336fc63a0d812caf/slick/src/main/scala/slick/util/ManagedArrayBlockingQueue.scala#L40)

Any ideas off the top of your head? Unfortunately, I don't have much time to spend on debugging this upgrade. Hopefully I'm just doing something obviously wrong?

```
[ERROR] Exception in thread "slick.db-7" Exception in thread "slick.db-8" java.lang.IllegalArgumentException: requirement failed: count cannot be increased
[ERROR] 	at scala.Predef$.require(Predef.scala:293)
[ERROR] 	at slick.util.ManagedArrayBlockingQueue.$anonfun$increaseInUseCount$1(ManagedArrayBlockingQueue.scala:40)
[ERROR] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[ERROR] 	at slick.util.ManagedArrayBlockingQueue.slick$util$ManagedArrayBlockingQueue$$locked(ManagedArrayBlockingQueue.scala:217)
[ERROR] 	at slick.util.ManagedArrayBlockingQueue.increaseInUseCount(ManagedArrayBlockingQueue.scala:39)
[ERROR] 	at slick.util.AsyncExecutor$$anon$2$$anon$1.beforeExecute(AsyncExecutor.scala:74)
[ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1139)
[ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[ERROR] 	at java.lang.Thread.run(Thread.java:745)
[ERROR] java.lang.IllegalArgumentException: requirement failed: count cannot be increased
[ERROR] 	at scala.Predef$.require(Predef.scala:293)
[ERROR] 	at slick.util.ManagedArrayBlockingQueue.$anonfun$increaseInUseCount$1(ManagedArrayBlockingQueue.scala:40)
[ERROR] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[ERROR] 	at slick.util.ManagedArrayBlockingQueue.slick$util$ManagedArrayBlockingQueue$$locked(ManagedArrayBlockingQueue.scala:217)
[ERROR] 	at slick.util.ManagedArrayBlockingQueue.increaseInUseCount(ManagedArrayBlockingQueue.scala:39)
[ERROR] 	at slick.util.AsyncExecutor$$anon$2$$anon$1.beforeExecute(AsyncExecutor.scala:74)
[ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1139)
[ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[ERROR] 	at java.lang.Thread.run(Thread.java:745)
 00:02:33.991UTC INFO  akka.actor.ActorSystemImpl akka.actor.ActorSystemImpl(flex) - HTTP server started on port 8088
 00:02:52.761UTC ERROR schaake.flex.actor.CreditActor akka://flex/user/$a/credits/$c - Persistence failure when replaying events for persistenceId [0b413f43-9ba6-4f1c-867b-5c9fd22cdd43]. Last known sequence number [0]
 akka.pattern.CircuitBreaker$$anon$1: Circuit Breaker Timed out.
 00:02:52.761UTC ERROR schaake.flex.actor.CreditActor akka://flex/user/$a/credits/$e - Persistence failure when replaying events for persistenceId [832d7955-a6d4-4457-b8bc-fb3cb6191f05]. Last known sequence number [0]
 akka.pattern.CircuitBreaker$$anon$1: Circuit Breaker Timed out.```

**Comment by dnvriend** [comment] 2017-02-25 02:50
Some questions: 
1. Does the journal contain old events?
2. Which serializer do you use when serializing / deserializing events to the journal ie JavaSerializer, Protobuf, Kryo, AVRO 
3. Does the project work when using scala 2.11.8
4 can you create a small project eg on github using your settings and reproduce the error?

**Comment by markschaake** [comment] 2017-02-25 03:44
Hi @dnvriend . Answers follow:

1. The journal does contain old events

2. I use Thrift for serialization of journal events

3. The project works with scala `2.11.8` - but using `akka-persistence-jdbc` version `2.6.12`. I've unsuccessfully tried briefly to get `2.4.17.1` to work on `2.11.8`. It seems the changes with Slick's driver/profile are confusing me too much.

4. If I have time I'll try to create a new project. I'm up against a deadline so won't likely have time to do this in the next week or so (sorry)

**Comment by dnvriend** [comment] 2017-02-25 06:59
@markschaake Have you tried setting the value of maxConnections like in my [postgres-application.conf](https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/test/resources/postgres-application.conf) but then increasing the settings to: 

- numThreads = 20
- maxConnections = 100
- minConnections = 20

It sounds like [slick issue #1461](https://github.com/slick/slick/pull/1461), [slick issue #1274](https://github.com/slick/slick/pull/1461), [slick issue #1614](https://github.com/slick/slick/issues/1614).

**Comment by markschaake** [comment] 2017-02-25 14:02
@dnvriend thanks, I had found those issues as well and was trying out different settings. With the settings you suggest, I no longer get the `java.lang.IllegalArgumentException: requirement failed: count cannot be increased`, but I still get the circuit breaker timeout error: 

`ERROR schaake.flex.actor.CreditActor akka://flex/user/$a/credits/$c - Persistence failure when replaying events for persistenceId [0b413f43-9ba6-4f1c-867b-5c9fd22cdd43]. Last known sequence number [0]
 akka.pattern.CircuitBreaker$$anon$1: Circuit Breaker Timed out.`

For these particular actors, they do not have any events in the journal to replay. I'm going to test my theory that there is a journal implementation bug that requires at least one event to replay per persisted actor. I'll let you know what I find out.

**Comment by markschaake** [comment] 2017-02-25 14:17
I think I was right about there being a bug in the journal that requires at least one event to reply per persisted actor. I tested this theory by creating events for all actors in my `2.11.8` branch and then switching back to my `2.12.1` branch. I no longer see the `Persistence failure when replaying events... Last known sequence number [0]...` anymore. However, that could be a red herring as now I'm seeing `AskTimeout`s. Wondering if those are caused by starved threads due to Slick (? no idea really ?).

**Comment by markschaake** [comment] 2017-03-24 17:23
I've finally got `akka-persistence-jdbc` working with slick `3.2.0`. Turns out was a copy/paste error combined with muted logging. The [`docker` database in the example postgres config](https://github.com/dnvriend/akka-persistence-jdbc/blob/4565ead80e228c61be8e9385b2252d74701277a6/src/test/resources/postgres-application.conf#L57) file snuck into my config for my `jdbc-journal`, but I didn't see the error of the missing database until I turned hikari log level to debug. Lesson (re)learned.

Also, along the debug path I ended up simplifying my config. I no longer specify max connections, relying on Slick's automatic config based on `numThreads` - which seems to work fine. Here's what I have:

```
db-base {
  host = "localhost"
  host = ${?DB_HOST}
  dbName = "myapp"
  user = "dev"
  user = ${?DB_USER}
  password = "localdev"
  password = ${?DB_PASSWORD}
  url = "jdbc:postgresql://"${db-base.host}":5432/${db-base.dbName}?reWriteBatchedInserts=true"
  profile = "slick.jdbc.PostgresProfile$"
  driver = "org.postgresql.Driver"
  numThreads = 3
}

app {
  db = ${db-base} {
    # App database access is minimal - only used to get seed IDs on startup. The rest is handled
    # by akka-persistence, which is configured with more threads (default of 3 in db-base)
    numThreads = 1
  }
}

... other config here including akka with serialization config
# Have all the journals use the same database connection config:
jdbc-journal.slick.db = ${db-base}
jdbc-snapshot-store.slick.db = ${db-base}
jdbc-read-journal.slick.db = ${db-base}
```

I'd vote to close this issue since it seems 2.12 support is working (at least for me).

**Closed** 2017-03-25 12:29 UTC
